### PR TITLE
Modify ProcessJSON to remove restriction to type map[string]string

### PR DESCRIPTION
**Pull request by relud**

### CODE REVIEW

**Comment by arnecls** [comment]
Could you change this to use shared.MarshalMap?
This type already takes care of type based constraints like this, so you can e.g. do valueMap.GetString().
Doing so would add this to our "maintenance chain" for type based marshaling.

**Comment by relud** [comment]
nevermind, I figured out a better path

**Comment by relud** [comment]
updated to use shared.MarshalMap instead of valueMap

**Comment by arnecls** [comment]
:+1:

**Pull request merged**
