### PR TITLE
add sample filter

### PR DESCRIPTION
**Pull request by relud**
This filter will accept `SampleRatePerGroup` out of every `SampleGroupSize` messages.

### CODE REVIEW

**Comment by arnecls** [comment]
So this is basically filter.Rate but binds all streams going through the filter to the same counter, correct? So when checking streams A and B filter.Rate will block only A if A goes over the limit. Your filter will block A and B if either A or B go over the limit, correct?

**Comment by relud** [comment]
while it is true that this doesn't filter per-stream, that's a side-effect of implementation. The desired effect is to rate limit as 2 of every 5 messages accept, instead of 2 messages per second accept.

**Comment by arnecls** [comment]
Ah, I see. Maybe this can be added to filter.Rate instead?
In that case you would get the per-stream rate automatically.

**Comment by arnecls** [comment]
On second thought ... nope - different usecase.

**Comment by arnecls** [comment]
I would like to the the "per stream count" extension in the future, otherwise fine.

**Pull request merged**
