### PR TITLE
http basic auth

### PR DESCRIPTION
**Pull request by glaslos**
Addition to the config:
```
Htpasswd: ".htpasswd"
BasicRealm: "test"
```
If Htpasswd file present, `401` error on authentication failure, `200` else.

### CODE REVIEW

**Comment by arnecls** [comment]
Code looks good to me.
Please add "github.com/abbot/go-http-auth" to the vendor folder using [gvt](https://github.com/FiloSottile/gvt) and add the changes.

**Comment by glaslos** [comment]
I should add that the basic auth check is rather expensive. With producer set to `Null`, this has a 10x overhead. There are for sure cheaper auth methods for HTTP (cookie?). Might be also worth to investigate HTTP2 which should add significant performance.

**Comment by arnecls** [comment]
Performance wise I've got no problem with this as the feature. It is optional and if someone decides to use an authenticated HTTP endpoint (and/or HTTPS), performance is probably not the first priority anyway.
In a high performance usecase a local UDS connection (consumer.Socket) with a buffered transfer to a secured, centralized backend service is probably a better idea.

**Comment by arnecls** [comment]
All approved: /merged
Thank you! :+1:

**Pull request merged**
