### PR TITLE
replacing net.websocket with gorilla.websocket

### PR DESCRIPTION
**Pull request by glaslos**
The old websocket producer was broken. In the godoc of net.websocket they recommend using gorilla.websocket: https://godoc.org/golang.org/x/net/websocket
I replace the old websocket handler with the gorilla one.
I also added an exclude in the .gitignore to add the license file, see #64

### CODE REVIEW

**Comment by arnecls** [comment]
That also sneaked in the license vendor rule ^^
Looks ok to me, we should just check if the golang.org/x/net/websocket can be removed now, too.

**Comment by glaslos** [comment]
I removed `net.websocket` from vendor.

**Comment by arnecls** [comment]
👍 I'll merge this once andy had a look at it too

**Pull request merged**
