### PR TITLE
#89 - Logrus evaluation / refactoring

### PR DESCRIPTION
**Pull request by ppar**
This PR addresses https://github.com/trivago/gollum/issues/89 by replacing tlog with the Logrus logging framework.

Not completely ready for merging yet, but the branch is here for comments & evaluation. Startup/shutdown handling, some TODOs and overall testing are still pending.

### CODE REVIEW

**Comment by ppar** [comment]
Relevant stuff at
- https://github.com/trivago/gollum/blob/enhancement/89-logrus/coordinator.go#L128-L130
- https://github.com/trivago/gollum/blob/enhancement/89-logrus/core/pluginconfigreaderwitherror.go#L41-L53
- https://github.com/trivago/gollum/blob/enhancement/89-logrus/core/logconsumer.go#L118-L163

**Comment by ppar** [comment]
Master merged, conflicts resolved.  Re-refactored changed plugins to use logrus instead of tlog.

TODO: `make test` still fails with  

`FAIL	github.com/trivago/gollum/core [build failed]` 

and also produces errors that apparently aren't being caught at all (see also https://github.com/trivago/gollum/issues/151):

```
time="2017-06-29T02:38:05+02:00" level=warning msg="JSON formatter has no directives setting" PluginID= PluginType=format.TextToJSON Scope=Formatter
time="2017-06-29T02:38:05+02:00" level=warning msg="State "findKey" has a transition to "" which does not exist in directives" PluginID=mockTextToJSONFormatter PluginType=format.TextToJSON Scope=Formatter
time="2017-06-29T02:38:05+02:00" level=warning msg="State "value" has a transition to "" which does not exist in directives" PluginID=mockTextToJSONFormatter PluginType=format.TextToJSON Scope=Formatter
time="2017-06-29T02:38:05+02:00" level=warning msg="State "array" has a transition to "" which does not exist in directives" PluginID=mockTextToJSONFormatter PluginType=format.TextToJSON Scope=Formatter
time="2017-06-29T02:38:05+02:00" level=warning msg="State "findKey" has a transition to "" which does not exist in directives" PluginID=mockTextToJSONFormatter PluginType=format.TextToJSON Scope=Formatter
time="2017-06-29T02:38:05+02:00" level=warning msg="State "value" has a transition to "" which does not exist in directives" PluginID=mockTextToJSONFormatter PluginType=format.TextToJSON Scope=Formatter
time="2017-06-29T02:38:05+02:00" level=warning msg="State "array" has a transition to "" which does not exist in directives" PluginID=mockTextToJSONFormatter PluginType=format.TextToJSON Scope=Formatter
time="2017-06-29T02:38:09+02:00" level=error msg="No stream configuration found. Please check your config." PluginID=prod0 PluginType=producer.ElasticSearch
```

**Comment by ppar** [comment]
Tests run ok, although some tests produce warnings in the log

**Comment by msiebeneicher** [comment]
@ppar : i added some small changes for the colors and timestamp - pls double check my [commit](https://github.com/trivago/gollum/pull/149/commits/5b711ae427235af6c9e681f11dcf9a156ee6e900)

In general the PR is fine now for me - i would suggest to provide some unit tests for the logger package

**Comment by msiebeneicher** [comment]
@arnecls : pls review this PR later ones

**Pull request merged**
