### PR TITLE
Fix for #103 Enabled shared config sessions for all AWS related plugins

### LINKED ISSUE #103: S3 Producer doesn't support AWS role switching
When using AWS STS credentials, `producer/s3.go` does not know how to switch to the required AWS STS role. 

Given a Gollum configuration:

```
"StdIn":
    Type: "consumer.Console"
    Streams: "console"
    Fuse: "file"

"S3Out":
    Type: "producer.S3"
    Region: "eu-central-1"
    CredentialType: "shared"
    CredentialFile: "/home/myusername/.aws/credentials"
    CredentialProfile: "test_profile"
    StreamMapping:
        "console": "my-testbucket/console"
        "*" : "my-testbucket/asterisk"
```

And an `~/.aws/credentials` file:

```
[test_profile]
aws_access_key_id = AKI.....
aws_secret_access_key = asdfgh1234
source_profile = default
role_arn = arn:aws:iam::123456789:role/foo-bar
region = eu-central-1
output = table
```

Gollum will simply try to connect using the default profile of that user and ignores the `role_arn` setting. 

There seems to be support for assuming roles in the AWS Go SDK:

https://github.com/aws/aws-sdk-go/blob/master/aws/credentials/stscreds/assume_role_provider.go

So it could be useful to add support for this in Gollum.

### PR DESCRIPTION
**Pull request by arnecls**
This change will allow gollum to be started like this:

```bash
AWS_DEFAULT_PROFILE=foobar gollum -c ...
```

This fixes #103 with a known way to change roles.

### CODE REVIEW

**Comment by arnecls** [comment]
Not tested on AWS, yet.

**Comment by msiebeneicher** [comment]
Change works for s3 producer as expected with example config from @ppar :

```yaml
"StdIn":
    Type: "consumer.Console"
    Streams: "console"
    Fuse: "file"

"S3Out":
    Type: "producer.S3"
    Region: "eu-central-1"
    CredentialType: "shared"
    CredentialFile: "/home/myusername/.aws/credentials"
    CredentialProfile: "test_profile"
    StreamMapping:
        "console": "my-testbucket/console"
```

**Comment by ppar** [comment]
Looks good. We should also mention this in the affected plugins' documentation (at least w/ a short note so that we'll remember to include it in the upcoming documentation rewrite).

**Comment by mahdi-hdi** [comment]
It doesn't work when you don't have an  `aws_access_key_id` or `aws_secret_access_key` in the config files (`~/.aws/credentials` or `~/.aws/config`). 
A use case is when you run an EC2 instance. You usually don't put any api_key in the instance, since it takes permission directly from AWS on startup so it's not necessary to provide any API key or even the `~/.aws/confg` file. In this case, any kinds of creating session or credential based on `~/.aws/confg` doesn't work because having the `aws_access_key_id` is a requirement for it.

**Comment by arnecls** [comment]
Hmm - in that case `CredentialType: "environment"` should work, shouldn't it?

**Comment by mahdi-hdi** [comment]
Based on the environment you are able to just load following variables:
https://github.com/aws/aws-sdk-go/blob/master/aws/session/env_config.go#L97
which is nothing related to assuming a role.

Moreover, by taking a look at how it merges different session configurations (file, env, ...) will find out assuming role without key and secret should be done (I guess) by [`stscreds.AssumeRoleProvider`](http://docs.aws.amazon.com/sdk-for-go/api/aws/credentials/stscreds/)

**Comment by arnecls** [comment]
@mahdi-hdi like this (see last commit)?

**Comment by mahdi-hdi** [comment]
Thanks, @arnecls. Now it looks good to me.

**Comment by arnecls** [comment]
Ok, @mahdi-hdi, @msiebeneicher did you test the latest version already on AWS?
If not I will do so tomorrow.

**Comment by mahdi-hdi** [comment]
Nope, will test it today.

**Comment by arnecls** [comment]
There is still some issues with the AssumeRole setting, but this looks more like an SDK related error than something broken on our side. Furthermore @mahdi-hdi got it running with Kinesis, so I assume it _should_ work.
If it does not, we need another fix. /merged

**Pull request merged**
