### PR TITLE
add KafkaGroup consumer

### PR DESCRIPTION
**Pull request by relud**
for #17

I need to test this more tomorrow.

### CODE REVIEW

**Comment by arnecls** [comment]
I'm currently scratching my head on how to improve that this is almost the same as the "normal" sarama producer. At the end this stuff should be possible with the standard sarama consumer, too ... at least from the concept behind it.
I'm a bit irritated that Shopify made this a separate package.

**Comment by relud** [comment]
after doing, I think I can see how to integrate this with the regular kafka consumer, as an option.

**Comment by arnecls** [comment]
I guess that would be better. This looks like we end up maintaining both code bases and based on my previous experience with sarama this is something that we definitely don't want to do ;)

**Comment by relud** [comment]
This is building properly, but it does not work at the moment.

**Comment by relud** [comment]
This is working for me when I run it with and without a consumer group set

**Comment by andygrunwald** [comment]
Awesome work @relud!

**Comment by arnecls** [comment]
Am I correct that this includes PR #44 ?
I will run this through our integration test suite tomorrow.

**Comment by arnecls** [comment]
integration tests 🆗

**Comment by relud** [comment]
no, pr #44 is for the kafka producer.

**Comment by arnecls** [comment]
stupid me.
So this will add groups AND authentication to the consumer.

**Comment by relud** [comment]
yes

**Pull request merged**
